import post from "../../images/post.jpg";
let DataLatestPost = [
  {
    image: post,
    title: "Side Effects of Percocet",
    name: "What Are the Dangers of Percocet Side Effects?",
    posted_by: "Ajay Prasad",
    link: "/blog/post1",
    time: "19 June, 2024",
    id: 1,
  },
  {
    image: post,
    title: "Side Effects of Percocet",
    name: "What Are the Dangers of Percocet Side Effects?",
    posted_by: "Ajay Prasad",
    link: "/blog/post1",
    time: "19 June, 2024",
    id: 2,
  },
  {
    image: post,
    title: "Side Effects of Percocet",
    name: "What Are the Dangers of Percocet Side Effects?",
    posted_by: "Ajay Prasad",
    link: "/blog/post1",
    time: "19 June, 2024",
    id: 3,
  },
  {
    image: post,
    title: "Side Effects of Percocet",
    name: "What Are the Dangers of Percocet Side Effects?",
    posted_by: "Ajay Prasad",
    link: "/blog/post1",
    time: "19 June, 2024",
    id: 4,
  },
  {
    image: post,
    title: "Side Effects of Percocet",
    name: "What Are the Dangers of Percocet Side Effects?",
    posted_by: "Ajay Prasad",
    link: "/blog/post1",
    time: "19 June, 2024",
    id: 5,
  },
  {
    image: post,
    title: "Side Effects of Percocet",
    name: "What Are the Dangers of Percocet Side Effects?",
    posted_by: "Ajay Prasad",
    link: "/blog/post1",
    time: "19 June, 2024",
    id: 6,
  },
  {
    image: post,
    title: "Side Effects of Percocet",
    name: "What Are the Dangers of Percocet Side Effects?",
    posted_by: "Ajay Prasad",
    link: "/blog/post1",
    time: "19 June, 2024",
    id: 7,
  },
  {
    image: post,
    title: "Side Effects of Percocet",
    name: "What Are the Dangers of Percocet Side Effects?",
    posted_by: "Ajay Prasad",
    link: "/blog/post1",
    time: "19 June, 2024",
    id: 8,
  },
  {
    image: post,
    title: "Side Effects of Percocet",
    name: "What Are the Dangers of Percocet Side Effects?",
    posted_by: "Ajay Prasad",
    link: "/blog/post1",
    time: "19 June, 2024",
    id: 9,
  },
  {
    image: post,
    title: "Side Effects of Percocet",
    name: "What Are the Dangers of Percocet Side Effects?",
    posted_by: "Ajay Prasad",
    link: "/blog/post1",
    time: "19 June, 2024",
    id: 10,
  },
  {
    image: post,
    title: "Side Effects of Percocet",
    name: "What Are the Dangers of Percocet Side Effects?",
    posted_by: "Ajay Prasad",
    link: "/blog/post1",
    time: "19 June, 2024",
    id: 11,
  },
  {
    image: post,
    title: "Side Effects of Percocet",
    name: "What Are the Dangers of Percocet Side Effects?",
    posted_by: "Ajay Prasad",
    link: "/blog/post1",
    time: "19 June, 2024",
    id: 12,
  },
];
export default DataLatestPost;
