import img from "../../images/Soma.jpg";
let DataProductGrid = [
  {
    image: img,
    title: "BUY TRAMADOL ONLINE",
    name: "TRAKEM 100MG",
    price: "340.00 – 410.00",
    sold_item: "119",
    link: "/buy-now",
    id: 1,
  },
  {
    image: img,
    title: "BUY TRAMADOL ONLINE",
    name: "TRAKEM 100MG",
    price: "340.00 – 410.00",
    sold_item: "119",
    link: "/buy-now",
    id: 2,
  },
  {
    image: img,
    title: "BUY TRAMADOL ONLINE",
    name: "TRAKEM 100MG",
    price: "340.00 – 410.00",
    sold_item: "119",
    link: "/buy-now",
    id: 3,
  },
  {
    image: img,
    title: "BUY TRAMADOL ONLINE",
    name: "TRAKEM 100MG",
    price: "340.00 – 410.00",
    sold_item: "119",
    link: "/buy-now",
    id: 4,
  },
  {
    image: img,
    title: "BUY TRAMADOL ONLINE",
    name: "TRAKEM 100MG",
    price: "340.00 – 410.00",
    sold_item: "119",
    link: "/buy-now",
    id: 5,
  },
  {
    image: img,
    title: "BUY TRAMADOL ONLINE",
    name: "TRAKEM 100MG",
    price: "340.00 – 410.00",
    sold_item: "119",
    link: "/buy-now",
    id: 6,
  },
  {
    image: img,
    title: "BUY TRAMADOL ONLINE",
    name: "TRAKEM 100MG",
    price: "340.00 – 410.00",
    sold_item: "119",
    link: "/buy-now",
    id: 7,
  },
  {
    image: img,
    title: "BUY TRAMADOL ONLINE",
    name: "TRAKEM 100MG",
    price: "340.00 – 410.00",
    sold_item: "119",
    link: "/buy-now",
    id: 8,
  },
  {
    image: img,
    title: "BUY TRAMADOL ONLINE",
    name: "TRAKEM 100MG",
    price: "340.00 – 410.00",
    sold_item: "119",
    link: "/buy-now",
    id: 9,
  },
  {
    image: img,
    title: "BUY TRAMADOL ONLINE",
    name: "TRAKEM 100MG",
    price: "340.00 – 410.00",
    sold_item: "119",
    link: "/buy-now",
    id: 10,
  },
  {
    image: img,
    title: "BUY TRAMADOL ONLINE",
    name: "TRAKEM 100MG",
    price: "340.00 – 410.00",
    sold_item: "119",
    link: "/buy-now",
    id: 11,
  },
  {
    image: img,
    title: "BUY TRAMADOL ONLINE",
    name: "TRAKEM 100MG",
    price: "340.00 – 410.00",
    sold_item: "119",
    link: "/buy-now",
    id: 12,
  },
];
export default DataProductGrid;
